apiVersion: apps/v1
kind: Deployment
metadata:
  name: animal-facts-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: animals
  template:
    metadata:
      labels:
        deployment: hello
    spec:
      containers:
      - name: python
        image: animal-facts:1.0
        ports:
        - containerPort: 5000
