apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: animal-app
spec:
  project: default
  source:
    path: argocd/kustomize
    repoURL: 'https://github.com/Lisa-Stats/animalFacts'
    targetRevision: HEAD
  destination:
    namespace: default
    server: 'https://kubernetes.default.svc'
