apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: animal-app
  namespace: argocd
spec:
  project: default
  source:
    path: argocd/kustomize
    repoURL: git@github.com:Lisa-Stats/animalFacts.git
    targetRevision: HEAD
  destination:
    namespace: default
    server: 'https://kubernetes.default.svc'
